<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <gazebo reference="laser_frame">    
        <sensor name='gpu_lidar' type='gpu_lidar'>"
            <pose relative_to='lidar_frame'>0 0 0 0 0 0</pose>
            <topic>lidar</topic>
            <update_rate>${lidar_update_rate}</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>300</samples>
                        <resolution>1</resolution>
                        <min_angle>${-lidar_hfov/2}</min_angle>
                        <max_angle>${lidar_hfov/2}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>${-lidar_vfov/2}</min_angle>
                        <max_angle>${lidar_vfov/2}</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>${lidar_max_range}</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>

.
    </gazebo>
    
</robot>