<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- For some reason this frame does not seem to work correctly -->
    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
    </link>
    
    <gazebo reference="laser_frame">    
        <sensor name='gpu_lidar' type='gpu_lidar'>"
            <pose relative_to='chassis'>${chassis_length+lidar_viz_cylinder_radius*2.1} 0 ${chassis_height*1.2} 0 0 0</pose>
            <topic>lidar</topic>
            <update_rate>${lidar_update_rate}</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>300</samples>
                        <resolution>1</resolution>
                        <min_angle>${-lidar_hfov/2}</min_angle>
                        <max_angle>${lidar_hfov/2}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>-0.01</min_angle>
                        <max_angle>0.01</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>${lidar_max_range}</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
.
    </gazebo>
    
</robot>